# --- PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/kinopoisk_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Hibernate ---
# none: Hibernate ?? ?????????? ? ?? ??????? ????? ? Flyway ???? ??????????
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Flyway ---
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# --- ?????? ---
server.port=8080

# --- ??????????? (??????? ??? ???????) ---
logging.level.org.hibernate.SQL=DEBUG