CREATE TABLE films (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(255) NOT NULL,
                       release_year INTEGER NOT NULL CHECK (release_year >= 1888 AND release_year <= 2030),
                       rating DOUBLE PRECISION NOT NULL CHECK (rating >= 0.0 AND rating <= 10.0)
);